### PR TITLE
Replace `behat/mink-extension` with `friends-of-behat/mink-extension`

### PR DESCRIPTION
**Pull request by Devristo**
Hey, thanks for this library! I had some problems upgrading my project to Symfony 5.3 / PHP 8. These were fixed by replacing [behat/mink-extension](https://github.com/Behat/MinkExtension) with [friends-of-behat/mink-extension](https://github.com/FriendsOfBehat/MinkExtension).

Advantages:

 * This is the fork of MinkExtension library that supports PHP ^7.2 and supports Symfony ^4.4 and ^5.0.

### CODE REVIEW

**Comment by rpkamp** [comment]
(closed and re-opened PR to kick off GitHub Actions)

**Comment by rpkamp** [comment]
I'm not sure if I should merge this. `friends-of-behat/mink-extension` already replaces `behat/mink-extension`. So if you install that in your project, this package will already use that instead. 

I'm not sure what impact it will have when we force everyone who uses this package to switch to `friends-of-behat/mink-extension` instead, if they haven't already done so. I fully agree that they should, but forcing people to do something is never nice.

**Comment by Devristo** [comment]
You are right, also I can no longer reproduce the composer error I had before. So I will close this issue.

**Comment by rpkamp** [comment]
Cool, thanks for getting back to me on this :+1:

**Pull request closed without merging**
